# filepath: c:\Users\NAMITHA RAVI\Desktop\api\render.yaml
services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 5001